name: Backend Deployment

on:
  push:
    branches:
      - main # Trigger deployment on push to the main branch

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.2

      - name: Deploy to Linode via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.LINODE_IP }}
          username: ${{ secrets.LINODE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

            cd /SportAppBackend || git clone https://github.com/${{ github.repository }}.git /SportAppBackend
            cd /SportAppBackend

            git pull origin main

            npm install

            npm run build

            pm2 restart all || pm2 start npm --name "backend" -- start
